name: Build and Publish
on: 
  push:
    tags:
      - "v*"

jobs:
    build:
        name: Build Deb file
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Build Docker container
              uses: docker/build-push-action@v6
              with:
                file: Dockerfile
                context: .
                push: false
                outputs: 'type=local,dest=.'

            - name: Release
              uses: softprops/action-gh-release@v2
              with:
                generate_release_notes: true
                files: ./*.deb