name: Build and Publish
on:
    workflow_dispatch
jobs:
    build:
        name: Build Deb file
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
